version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    env_file:
      - .env

