FROM python:3.11

ENV PYTHONUNBUFFERED 1
ENV PYTHONPATH=/backend

WORKDIR /backend

COPY requirements.txt /backend/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /backend/

EXPOSE 8000

CMD ["python", "src/manage.py", "runserver", "0.0.0.0:8000"]

