# Generated by Django 5.1.2 on 2024-10-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.IntegerField(verbose_name='Telegram User ID')),
                ('user_command', models.CharField(max_length=255, verbose_name='User command')),
                ('bot_response', models.TextField(verbose_name='Response from bot')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['telegram_user_id'], name='logs_userlo_telegra_76d9ed_idx')],
            },
        ),
    ]
